language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

  
script:
  - docker --version # print the version for logging
  - docker build -t udagram_user_api .
  - docker tag udagram_user_api forsythetony/udagram_user_api:latest

after_success:
  - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  - docker push forsythetony/udagram_user_api
